[project]
name = "volbomzutter"
version = "1.0.0"
description = "Simple blogging web-app."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"